#!/bin/bash
set -eux

DOCKERROOT=$(docker info --format '{{ '{{ .DockerRootDir }}' }}')
PCENT=$(df --output=pcent $DOCKERROOT | tail -1 | sed 's/^[ ]*\([0-9]*\)%/\1/')
systemd-cat -t clear-log echo $PCENT percent used

{% for volume in volumes %}

JOBLOG="$(docker volume inspect --format '{{ '{{ .Mountpoint }}' }}' {{ volume }})/var/job"

if [ -d $JOBLOG ] ; then

        if [ $PCENT -gt 90 ] ; then
                OLDEST=`ls -d $JOBLOG/* | head -1`
                systemd-cat -t clear-log echo Removing $OLDEST
                systemd-cat -t clear-log rm -r $OLDEST
        fi

fi

{% endfor %}
