---
- hosts: staging.ci.dev
  name: Set up Docker
  roles:
    - docker
    - deployer-key

- hosts: staging.ci.dev
  name: Set up SwarmKit
  tasks:
    - docker_swarm:
        listen_addr: "127.0.0.1:2377"
        advertise_addr: "127.0.0.1:2377"

- hosts: staging.ci.dev
  name: Deploy staging site for OCaml.org
  tasks:
    - name: create varnish directory
      file:
        path: /etc/varnish
        state: directory
    - name: configure varnish
      copy:
        dest: /etc/varnish/default.vcl
        content: |
          vcl 4.1;

          import proxy;
          import directors;

          # For dynamic backends
          # See https://github.com/nigoroll/libvmod-dynamic/blob/master/src/vmod_dynamic.vcc
          import dynamic;

          # Probe for updates to backend server
          probe www_probe {
            .interval = 5s;
            .timeout = 1s;
            .window = 5;
            .threshold = 3;
            .initial = 3;
          }

          probe health {
              .url = "/";
          }

          sub vcl_init {
              new ocaml_org = dynamic.director(
                port = "8080",
                probe = www_probe,
                ttl = 5m,
              );
              new vdir = directors.round_robin();
              vdir.add_backend(ocaml_org.backend("www1"));
              vdir.add_backend(ocaml_org.backend("www2"));
          }

          sub vcl_recv {
              if ((req.http.X-Forwarded-Proto && req.http.X-Forwarded-Proto != "https") || 
                  (req.http.Scheme && req.http.Scheme != "https")) {
                  return (synth(750));
              } elseif (!req.http.X-Forwarded-Proto && !req.http.Scheme && !proxy.is_ssl()) {
                  return (synth(750));
              }
          }

          sub vcl_synth {
              if (resp.status == 750) {
                  set resp.status = 301;
                  set resp.http.location = "https://" + req.http.Host + req.url;
                  set resp.reason = "Moved";
                  return (deliver);
              }
          }

    - name: install docker-prune script
      copy:
        src: cron-scripts/docker-prune
        dest: /etc/cron.hourly/docker-prune
        mode: u=rwx,g=rx,o=rx

    - name: set up infrastructure stack
      docker_stack:
        name: infra
        prune: yes
        compose:
          - version: "3.7"
            services:
              hitch:
                deploy:
                  mode: global
                ports:
                  - target: 443
                    published: 443
                    protocol: tcp
                    mode: host
                image: hitch:latest
                command: "--backend=[varnish]:8080"
                volumes:
                  - "/etc/hitch/cert.pem:/etc/hitch/testcert.pem:ro"

              varnish:
                deploy:
                  mode: global
                ports:
                  - target: 80
                    published: 80
                    protocol: tcp
                    mode: host
                image: varnish:stable
                volumes:
                  - "/etc/varnish/default.vcl:/etc/varnish/default.vcl"
                tmpfs:
                  - /var/lib/varnish:exec
                environment:
                  - VARNISH_SIZE=2G
                command: "-a :8080,PROXY -p default_keep=300 -p feature=+http2"

              www1:
                image: ocurrent/v3.ocaml.org-server:staging
                sysctls:
                  - "net.ipv4.tcp_keepalive_time=60"

              www2:
                image: ocurrent/v3.ocaml.org-server:staging
                sysctls:
                  - "net.ipv4.tcp_keepalive_time=60"
